version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: fullmart
      POSTGRES_PASSWORD: fullmart
      POSTGRES_DB: fullmart_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
#  --- IGNORE ---